version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - PHIL

  starwars_api:
    build:
      context: .
    container_name: starwars-api
    networks:
      - PHIL
    command: tail -f /dev/null

networks:
  PHIL:
    driver: bridge
